# Generated by Django 2.1.7 on 2019-05-20 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='birth_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='apply',
            name='courses_in_programme',
            field=models.CharField(choices=[('AP', 'Computer Appreciation'), ('PD', 'Python with Django'), ('MT', 'Computer Maintenance')], default='AP', max_length=2),
        ),
        migrations.AddField(
            model_name='apply',
            name='phone',
            field=models.CharField(default='0000000', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='othernames',
            field=models.CharField(max_length=50, verbose_name='Other Names'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Surname'),
        ),
    ]
