# Generated by Django 2.2.1 on 2019-05-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0005_apply_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='birth_date',
            field=models.DateField(max_length=20, verbose_name='Date of Birth'),
        ),
    ]
