# Generated by Django 2.2.1 on 2019-05-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0006_auto_20190521_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='courses_in_programme',
            field=models.CharField(choices=[(-1, '--Select Programme--'), ('AP', 'Computer Appreciation'), ('PD', 'Python with Django'), ('MT', 'Computer Maintenance')], default='AP', max_length=2),
        ),
    ]
