# Generated by Django 2.2.1 on 2019-05-21 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0008_auto_20190521_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
