# Generated by Django 2.2.1 on 2019-05-23 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0010_auto_20190521_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='isApplicationSubmitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apply',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apply',
            name='birth_date',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
    ]
