# Generated by Django 2.2.1 on 2019-06-06 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cusers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='surname',
        ),
    ]
