# Generated by Django 2.2.1 on 2019-06-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusers', '0004_auto_20190606_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
