# Generated by Django 2.2.1 on 2019-06-07 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cusers', '0005_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Courses_Programme',
            new_name='Programme_Course',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='courses_programme',
            new_name='programme_course',
        ),
        migrations.CreateModel(
            name='Local_Government_Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cusers.State')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='local_government_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cusers.Local_Government_Area'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cusers.State'),
        ),
    ]
