# Generated by Django 2.2.1 on 2020-01-13 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cusers', '0006_auto_20190607_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='programmeCourse',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='cusers.Programme_Course'),
            preserve_default=False,
        ),
    ]
