# Generated by Django 2.2.1 on 2020-01-13 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cusers', '0009_programme_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='programme_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cusers.Programme_Session'),
        ),
    ]
