# Generated by Django 2.2.1 on 2020-02-26 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cusers', '0012_auto_20200113_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme_course',
            name='description',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='academic_session',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cusers.Programme_Session'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='programme_Course',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='cusers.Programme_Course'),
        ),
    ]
