# Generated by Django 2.2.8 on 2020-03-04 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cusers', '0013_auto_20200226_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='programme_session',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cusers.Programme_Session'),
        ),
    ]
