"""
Django settings for django_projects project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
#import django_heroku

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0%$v8&)*te+8ac6)1his4@a#x#g4)1_z+&&glc+l4_qrqzj^ug'

# SECURITY WARNING: don't run with debug turned on in production!
# I need to change this debug true in production. I will do that just calm down.
# Tinubu is a thief. We need to probe him and send him to jail. We need Mrs. stella to be our next president
# Meanwhile, Mr. Oyedele will now be the new EFCC chairman
DEBUG = False

ALLOWED_HOSTS = ['.register.oaucdl.edu.ng']


# Application definition

INSTALLED_APPS = [
    'users.apps.UsersConfig',
    'biodata.apps.BiodataConfig',
    # 'tutorials.apps.TutorialsConfig',
    'cusers.apps.CusersConfig', # new
    'blog.apps.BlogConfig',
    'apply.apps.ApplyConfig',
    'payment.apps.PaymentConfig',
    'reports.apps.ReportsConfig',
    'results.apps.ResultsConfig',
    'security.apps.SecurityConfig',
    'crispy_forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'requests',
    'django_tables2',
    'django_filters',
    'bootstrapform',
    'bootstrap4',
    'session_security',
       
]

MIDDLEWARE = [
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'session_security.middleware.SessionSecurityMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'django_projects.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_projects.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'oaucdl_applyportal',
        'USER': 'oaucdl_newuser',
        'PASSWORD': 'BYyJ5krhze9jf0Gd',
        'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


DATE_INPUT_FORMATS = ['%d-%m-%Y']

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)

# Static asset configuration
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = 'staticfiles'
STATICFILES_DIRS = (
os.path.join(BASE_DIR, 'static'),
)


# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

CRISPY_TEMPLATE_PACK = 'bootstrap4'
DJANGO_TABLES2_TEMPLATE = 'django_tables2/bootstrap-responsive.html'
LOGIN_REDIRECT_URL = 'profile'
LOGIN_URL = 'login'
AUTH_USER_MODEL = 'cusers.CustomUser' # new


PAYSTACK_PUBLIC_KEY = "pk_test_39ee1fc41decc477bd39aac2969ced349150fcfd" #os.environ['PAYSTACK_PUBLIC_KEY']
PAYSTACK_SECRET_KEY = "sk_test_d896feaf700610993e855f7a66e7c0fc3e45ace9" #os.environ['PAYSTACK_SECRET_KEY']
# PAYSTACK_FAILED_URL = "/google/api"
# PAYSTACK_SUCCESS_URL = "/google/api"
PAYSTACK_WEBHOOK_DOMAIN = 'tuteria.ngrok.io'




EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASS')


SESSION_SECURITY_WARN_AFTER = 540
SESSION_SECURITY_EXPIRE_AFTER = 600
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

