# Generated by Django 2.2.1 on 2019-05-23 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('firstname', models.CharField(max_length=50, verbose_name='First Name')),
                ('othernames', models.CharField(max_length=50, verbose_name='Other Names')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('birth_date', models.DateField(verbose_name='Date of Birth')),
                ('isApplicationSubmitted', models.BooleanField(default=False)),
                ('courses_in_programme', models.CharField(choices=[(-1, '--Select Programme--'), ('AP', 'Computer Appreciation'), ('PD', 'Python with Django'), ('MT', 'Computer Maintenance')], default=-1, max_length=2)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
