# Generated by Django 2.2.1 on 2019-05-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0002_remove_personalinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='isApplicationCreated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='othernames',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Other Names'),
        ),
    ]
