# Generated by Django 2.2.1 on 2019-06-03 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0003_auto_20190523_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Local_Government_Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biodata.State')),
            ],
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='local_government_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biodata.Local_Government_Area'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biodata.State'),
        ),
    ]
