# Generated by Django 2.2.1 on 2019-06-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0004_auto_20190603_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local_government_area',
            name='state',
            field=models.CharField(max_length=30),
        ),
    ]
