# Generated by Django 2.2.1 on 2019-06-03 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0005_auto_20190603_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local_government_area',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biodata.State'),
        ),
    ]
