# Generated by Django 2.2.1 on 2019-06-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0007_auto_20190606_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='application_number',
            field=models.CharField(default='OAUCDL00001', editable=False, max_length=120, unique=True),
        ),
    ]
