# Generated by Django 2.2.1 on 2019-06-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0009_auto_20190606_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='application_number',
            field=models.CharField(default='A00001', editable=False, max_length=150, unique=True),
        ),
    ]
