# Generated by Django 2.2.1 on 2019-06-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0011_auto_20190606_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='application_number',
            field=models.CharField(default='A01', editable=False, max_length=10, unique=True),
        ),
    ]
