# Generated by Django 2.2.1 on 2019-06-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0013_auto_20190606_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='application_number',
        ),
    ]
