# Generated by Django 2.2.1 on 2019-06-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0014_remove_personalinfo_application_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='isApplicationCreated',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='isApplicationSubmitted',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='othernames',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='surname',
        ),
    ]
